config/routes.rb
Deej::Application.routes.draw do
  resources :songs do
    get :queue, on: :collection
    get :download, on: :member
    resources :votes
  end

  root to: "songs#index"
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :album, :artist, :length, :genre, :path, :play_count, :title, :playing

  has_many :votes

  def self.search query
    where "title LIKE :q OR artist LIKE :q OR path LIKE :q OR genre LIKE :q", q: "%#{query}%"
  end

  def self.playing
    where('playing is NOT NULL').first
  end

  # Sort songs by number of votes then earliest vote
  def self.queue
    find_by_sql %q{
      select s.*, vote_count
      from songs s,
        (select count(*) as vote_count, song_id, min(created_at) as created_at
         from votes
         where status='active'
         group by song_id) v
      where s.id=v.song_id order by v.created_at
    }
  end

  def self.next
    queue.first || random
  end

  def self.random
    order('RANDOM()').first
  end

  def self.stop_playing!
    self.update_all playing: nil
    Vote.skips.update_all status: 'old_skip'
  end

  def to_s
    "#{artist} - #{title}"
  end

  def current_percent
    ((elapsed / length.to_f) * 100).to_i
  end

  def elapsed
    (Time.now - playing).floor
  end

  # Not sure where to put this but Song.playing.current_listeners seemed ok
  def current_listeners
    return @current_listeners if @current_listeners
    return if CONFIG['icecast']['admin_user'].blank?

    # admin_url is set in the app config initializer as a "helper"
    xml = open(CONFIG['icecast']['admin_url'] + "/listclients?mount=#{CONFIG['icecast']['mount']}",
          http_basic_authentication: [CONFIG['icecast']['admin_user'],CONFIG['icecast']['admin_pass']])
    stats = Hash.from_xml xml.read

    @current_listeners = stats['icestats']['source']['Listeners'].to_i
  end

  def skip?
    votes.skips.count > 0 && votes.skips.count >= current_listeners / 2
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :ip, :status

  validates :ip, uniqueness: {scope: [:status, :song_id]}
  validates :status, inclusion: { in: %w{active skip played old_skip}}

  belongs_to :song

  scope :active, where(status: 'active')
  scope :skips,  where(status: 'skip')
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.order('artist, album').page(params[:page]).per(20)

    if params[:query]
      @songs = @songs.search params[:query]
    end
  end

  def queue
    respond_to do |format|
      format.html { render partial: 'queue'}
      format.json do
        render json: {
          playing: Song.playing.to_s,
          listeners: Song.playing.current_listeners
        }.to_json
      end
    end
  end

  def download
    song = Song.find params[:id]
    song.downloads += 1
    song.save

    send_data open(song.path).read, filename: File.basename(song.path)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def new
    @song = Song.find params[:song_id]

    @vote = @song.votes.new ip: request.remote_ip
    @vote.status = params[:status] if params[:status]
    @vote.save
  end

  def destroy
    @song = Song.find params[:song_id]

    @vote = Vote.find params[:id]
    @vote.destroy

    render action: :new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
  def format_time seconds
    minutes, seconds = seconds.divmod 60
    hours, minutes = minutes.divmod 60

    pad = ->(x) {x.to_s.rjust 2, '0'}

    if hours > 0
      "#{hours}:#{pad[minutes]}:#{pad[seconds]}"
    else
      "#{minutes}:#{pad[seconds]}"
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Deej" %></title>
    <%= csrf_meta_tags %>

    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-static-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">Deej</a>

          <div class="container nav-collapse">
            <form class="navbar-search pull-right">
              <input type="text" class="search-query" placeholder="Search">
              <i id="cancel-search" class="icon-remove"></i>
            </form>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span9">
            <%= yield %>
           </div>
           <div class="span3">
             <div class="well" style="text-align: center">
               <a href="<%= CONFIG['icecast']['full_url'] %>" class="btn btn-success btn-large">
                 Click here to listen!
               </a>
             </div>
             <div id="queue" class="well">
               <%= render 'songs/queue' %>
             </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->
    </div><!-- /container -->

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/songs/_queue.html.erb
<h3>Currently Playing</h3>

<% if @playing = Song.playing %>
<%= @playing %>
<div class="progress progress-striped active">
  <div class="bar" style="width: <%= @playing.current_percent %>%"></div>
</div>

<div id="current_progress">
  <%= format_time @playing.elapsed %> /
  <%= format_time @playing.length %>
</div>

Current listeners: <%= @playing.current_listeners %><br />

<%= link_to 'Vote to skip this song', new_song_vote_path(@playing, status: 'skip'), remote: true %>
(<%= @playing.votes.skips.count %> / <%= @playing.current_listeners > 1 ? @playing.current_listeners / 2 : 1 %> needed)
<% else %>
The radio is currently off.
<% end %>
<br />
<h3>Queue</h3>
<ul class="nav nav-list">
  <!-- <li class="nav-header">Sidebar</li> -->
  <% Song.queue.each do |song| %>
    <li><%= song.vote_count %> <%= song %></li>
  <% end %>
  <% if Song.queue.empty? %>
  The queue is currently empty. Songs will be chosen from the library at random.
  <% end %>
</ul>

<script type="text/javascript" charset="utf-8">
  elapsed     = <%= @playing.try(:elapsed) || 'null' %>;
  song_length = <%= @playing.try(:length)  || 'null' %>;
</script>

app/views/songs/_song.html.erb
<tr id="song_<%= song.id %>">
  <td><%= song.artist %></td>
  <td><%= link_to song.title, download_song_path(song) %></td>
  <td><%= format_time song.length %></td>
  <td>
    <% if vote = song.votes.active.where(ip: request.remote_ip).first %>
    <%= link_to 'Remove your vote', song_vote_path(song, vote), method: :delete, remote: true, class: 'btn btn-mini btn-danger vote' %>
    <% elsif song.votes.skips.where(ip: request.remote_ip).count > 0 %>
    <span class="label label-warning">You voted to skip this song!</span>
    <% elsif song.playing? %>
    <span class="label label-success">This song is playing!</span>
    <% else %>
    <%= link_to 'Vote', new_song_vote_path(song), remote: true, class: 'btn btn-mini btn-primary vote', id: "vote_#{song.id}" %>
    <% end %>
  </td>
</tr>

app/views/songs/_table.html.erb
<table class="table table-condensed">
  <tr>
    <th class="artist_column">Artist</th>
    <th>Title</th>
    <th class="length_column">Length</th>
    <th class="vote_column">Vote</th>
  </tr>

  <%= render @songs %>
</table>

<%= paginate @songs, remote: true %>

app/views/songs/index.html.erb
<div id="song_list">
  <%= render 'table' %>
</div>

app/views/songs/index.js.erb
$('#song_list').html('<%= escape_javascript(render 'table') %>');

app/views/votes/new.js.erb
<% if @vote %>
  $('#queue').html('<%= escape_javascript(render 'songs/queue') %>');
  $('#song_'+<%= @song.id %>).replaceWith('<%= escape_javascript(render partial: 'songs/song', object: @song) %>');
  highlight_selected_song();
<% end %>